
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MKN_KUL_GIT_CO: --depth 1
  CURL_GET: curl -fL --retry 3 --retry-delay 2
  PATH_GET: https://github.com/mkn/mkn/releases/download/latest

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: |
        $CURL_GET -o mkn ${PATH_GET}/mkn_nix
        chmod +x mkn
        KLOG=2 ./mkn clean build run -dtOa "-std=c++20 -fPIC"
        KLOG=3 ./mkn -p test

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - run: |
        $CURL_GET -o mkn ${PATH_GET}/mkn_arm_osx
        chmod +x mkn
        KLOG=2 ./mkn clean build run -dtOa "-std=c++20 -fPIC"
        KLOG=3 ./mkn -p test
